### ISSUE TITLE
Set up express with the database and deploy it to heroku

### ISSUE THREAD

**Issue by JackyLiu97** [ChibiKev/Split-It#3]
I think its a good idea to set up the database with express and deploy it to heroku so everyone don't have to set up the database locally on their machine.

**Comment by ChibiKev** [comment]
As of now, we don't have much of a database to work with. We need to come up with a database structure first before we jump into it. We shouldn't waste our time on things we aren't going up to yet because the structure might change as we progress.
First working on the frontend and backend with a design or format in mind of the structure.
Then implementing the structure, and having it be correctly routed and functional.
