### ISSUE TITLE
Authentication Refresh Bug

### ISSUE THREAD

**Issue by JackyLiu97** [ChibiKev/Split-It#97]
PROBLEM: When you refresh the page, it seems the whole state of react refreshes and thus the whole react state returns to default. In the root node, the variable isAuthenticated resets to false if a logged in user refreshes the page.

SOLUTION: I will try to investigate why react is behaving this way. Maybe a boolean variable is not enough to enforce the check. We can add a harder condition on checks to enforce the boolean variable stays true I guess.
God knows lol

**Comment by ChibiKev** [comment]
Your solution was incorrect and would have no way of it working. Nice try tho.
My solution. Since you store the token as local storage. I will try to access that local storage. If there is a token, I will retrieve the data in that token and use that data for the states to keep the user logged in. If there is not a token, then there is no user.
